---
- name: Set SELinux to disabled state
  selinux:
    state: disabled
  when: ansible_distribution in ['CentOS', 'RedHat', 'Red Hat Enterprise Linux']

- name: Set File max_user_watches limits
  sysctl:
    name: fs.inotify.max_user_watches
    value: "2099999999"
    state: present
    reload: yes
  
- name: Set File max_user_instances limits
  sysctl:
    name: fs.inotify.max_user_instances
    value: "2099999999"
    state: present
    reload: yes

- name: Set File max_queued_events limits
  sysctl:
    name: fs.inotify.max_queued_events
    value: "2099999999"
    state: present
    reload: yes

- name: Enable IPv4 forwarding
  sysctl:
    name: net.ipv4.ip_forward
    value: "1"
    state: present
    reload: yes

- name: Enable IPv6 forwarding
  sysctl:
    name: net.ipv6.conf.all.forwarding
    value: "1"
    state: present
    reload: yes
  when: ansible_all_ipv6_addresses | length > 0

- name: Add br_netfilter to /etc/modules-load.d/
  copy:
    content: "br_netfilter"
    dest: /etc/modules-load.d/br_netfilter.conf
    mode: "u=rw,g=,o="
  when: ansible_distribution in ['ArchLinux', 'CentOS', 'RedHat', 'Red Hat Enterprise Linux']

- name: Load br_netfilter
  modprobe:
    name: br_netfilter
    state: present
  when: ansible_distribution in ['ArchLinux', 'CentOS', 'RedHat', 'Red Hat Enterprise Linux']

- name: Set bridge-nf-call-iptables (just to be sure)
  sysctl:
    name: "{{ item }}"
    value: "1"
    state: present
    reload: yes
  when: ansible_distribution in ['ArchLinux', 'CentOS', 'RedHat', 'Red Hat Enterprise Linux']
  loop:
    - net.bridge.bridge-nf-call-iptables
    - net.bridge.bridge-nf-call-ip6tables

- name: Add {{ bin_dir }} to sudo secure_path
  lineinfile:
    line: 'Defaults    secure_path = /sbin:/bin:/usr/sbin:/usr/bin:{{ bin_dir }}'
    regexp: "Defaults(\\s)*secure_path(\\s)*="
    state: present
    insertafter: EOF
    path: /etc/sudoers
    validate: 'visudo -cf %s'
  when: ansible_distribution in ['CentOS', 'RedHat', 'Red Hat Enterprise Linux']

- name: Wait for automatic system updates
  shell: while fuser /var/lib/dpkg/lock >/dev/null 2>&1; do sleep 10; done;
  when: ansible_distribution in ['Ubuntu']

- name: Install additional packages
  package:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  with_items: "{{ install_additional_packages | default([]) }}"

- name: Enable additional services
  ansible.builtin.systemd:
    name: "{{ item }}"
    enabled: yes
    masked: no
  with_items: "{{ enable_additional_services | default([]) }}"

- name: Start additional services
  ansible.builtin.systemd:
    state: started
    name: "{{ item }}"
  with_items: "{{ enable_additional_services | default([]) }}"

- name: install custom facts module
  include_role:
    name: facts
    apply:
      tags:
        - always
  tags:
    - always

- name: install driver
  include_role:
    name: nvidia.nvidia_driver
    apply:
      tags:
        - nvidia_driver
  when: ansible_local.gpus.count
  tags:
    - always

- name: install libnvidia-container
  include_role:
    name: libnvidia-container-tools
    apply:
      tags:
        - libnvidia_container
  when: ansible_local.gpus.count
  tags:
    - always
